from __future__ import annotations

from json import dumps
import re
from typing import List

from langchain_core.prompts import ChatPromptTemplate

from app.models import (
    AgentSessionState,
    RepairContext,
    AppSpec,
    BuildWebAppStep,
    FileChange,
    GeneratedCodeOutput,
    GitSnapshotStep,
    InstallDependenciesStep,
    StartPreviewStep,
    StopPreviewStep,
    WorkspaceFile,
)
from app.services.errors import GenerationFailure
from app.services.json_parser import parse_json_response
from app.services.model_provider import ModelProvider


class CodeGenerationService:
    def __init__(self) -> None:
        self.provider = ModelProvider()

    def generate(self, state: AgentSessionState, spec: AppSpec, workspace_snapshot: List[WorkspaceFile]) -> AgentSessionState:
        generation = self._invoke_generation(state, spec, workspace_snapshot)
        return self._apply_generation_result(state, generation, spec.title)

    def repair(
        self,
        state: AgentSessionState,
        spec: AppSpec,
        workspace_snapshot: List[WorkspaceFile],
        repair_context: RepairContext,
    ) -> AgentSessionState:
        relevant_paths = self._derive_relevant_paths(workspace_snapshot, repair_context.build_error)
        repair_snapshot = self._select_repair_snapshot(workspace_snapshot, relevant_paths)
        generation = self._invoke_repair(state, spec, repair_snapshot, repair_context, relevant_paths)
        return self._apply_generation_result(
            state,
            generation,
            spec.title,
            default_summary_prefix=f"Repair {repair_context.attempt} for",
        )

    def _apply_generation_result(
        self,
        state: AgentSessionState,
        generation: GeneratedCodeOutput,
        title: str,
        default_summary_prefix: str = "Generate",
    ) -> AgentSessionState:
        files = [
            FileChange(
                path=item.path,
                action="write",
                content=item.content,
                summary=item.summary or f"Write {item.path} generated by Qwen.",
            )
            for item in generation.files
        ]
        files.extend(
            FileChange(path=path, action="delete", summary=f"Remove {path} because it is no longer needed.")
            for path in generation.delete_paths
        )
        state.file_changes = files
        state.file_change_summary = [change.summary for change in files]
        state.assistant_summary = generation.assistant_summary or f"{default_summary_prefix} {title}"
        state.execution_manifest = [
            StopPreviewStep(type="stop_preview", description="Stop any previous preview for this project."),
            InstallDependenciesStep(
                type="install_dependencies",
                description="Install the app dependencies with npm.",
                packageManager="npm",
            ),
            BuildWebAppStep(
                type="build_web_app",
                description="Run a production build as a verification step.",
                packageManager="npm",
            ),
            StartPreviewStep(
                type="start_vite_preview",
                description="Start the Vite development server for interactive preview.",
                packageManager="npm",
                port=4173,
            ),
            GitSnapshotStep(
                type="git_snapshot",
                description="Commit the generated version into the project workspace repository.",
                message=f"Generate version {state.version_number + 1}: {title}",
            ),
        ]
        return state

    def _invoke_generation(
        self, state: AgentSessionState, spec: AppSpec, workspace_snapshot: List[WorkspaceFile]
    ) -> GeneratedCodeOutput:
        prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    "You are generating production-ready React + Vite TypeScript code. "
                    "Return structured output only. Your response must be valid JSON that matches the requested schema. "
                    "Do not wrap the JSON in markdown fences. "
                    "Return a JSON object with keys: assistantSummary, files, deletePaths. "
                    "Each file object must contain path, content, summary. "
                    "No placeholders, no TODOs, no template markers. "
                    "If the workspace is empty, create a complete runnable app from scratch. "
                    "If the workspace already has files, modify only the files that must change to satisfy the latest request. "
                    "The result must build with npm install && npm run build and run with npm run dev.",
                ),
                (
                    "human",
                    "Latest conversation:\n{messages}\n\n"
                    "Normalized app spec:\n{spec}\n\n"
                    "Current workspace snapshot:\n{workspace}\n\n"
                    "Fresh project required files: package.json, tsconfig.json, vite.config.ts, index.html, src/main.tsx, src/App.tsx. "
                    "Add any extra files you need, such as stylesheets or components. "
                    "Return only the files to write or replace and any delete paths that should be removed.",
                ),
            ]
        )

        try:
            model = self.provider.require_chat_model()
            messages = prompt.format_messages(
                messages=dumps([message.model_dump(mode="json") for message in state.messages], ensure_ascii=False),
                spec=dumps(spec.model_dump(mode="json", by_alias=True), ensure_ascii=False),
                workspace=dumps(
                    [item.model_dump(mode="json") for item in workspace_snapshot],
                    ensure_ascii=False,
                ),
            )
            response = model.invoke(messages)
            return parse_json_response(response.content, GeneratedCodeOutput)
        except Exception as exc:
            if isinstance(exc, GenerationFailure):
                raise
            raise GenerationFailure(f"Qwen request failed while generating code: {exc}") from exc

    def _invoke_repair(
        self,
        state: AgentSessionState,
        spec: AppSpec,
        workspace_snapshot: List[WorkspaceFile],
        repair_context: RepairContext,
        relevant_paths: List[str],
    ) -> GeneratedCodeOutput:
        prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    "You are repairing a React + Vite TypeScript project generated by a coding agent. "
                    "Return structured output only. Your response must be valid JSON that matches the requested schema. "
                    "Do not wrap the JSON in markdown fences. "
                    "Return a JSON object with keys: assistantSummary, files, deletePaths. "
                    "Each file object may contain path, content, and optional summary. "
                    "Make the smallest set of code changes needed to fix the reported build failure. "
                    "Preserve the product intent and avoid rewriting unrelated files. "
                    "The output is applied verbatim and rebuilt immediately, so every listed diagnostic must be fixed in the returned code. "
                    "Do not describe a fix unless the returned file contents actually implement it. "
                    "When a React Router page needs a route parameter, prefer reading it with useParams instead of requiring an extra prop passed directly from a Route element.",
                ),
                (
                    "human",
                    "Normalized app spec:\n{spec}\n\n"
                    "Files most likely needing changes:\n{relevant_paths}\n\n"
                    "Relevant workspace snapshot:\n{workspace}\n\n"
                    "Latest build failure context:\n"
                    "Attempt: {attempt}\n"
                    "Failed command: {failed_command}\n"
                    "Build output:\n{build_error}\n\n"
                    "Repair checklist:\n"
                    "1. Fix every TypeScript/build diagnostic shown above.\n"
                    "2. If a dependency is missing, update package.json.\n"
                    "3. If a component prop is missing in JSX, either pass it correctly or refactor the component so the JSX is valid.\n"
                    "4. Return only the files that must change to make npm run build succeed.\n"
                    "5. Do not return unchanged files.",
                ),
            ]
        )

        try:
            model = self.provider.require_chat_model()
            messages = prompt.format_messages(
                spec=dumps(spec.model_dump(mode="json", by_alias=True), ensure_ascii=False),
                workspace=dumps(
                    [item.model_dump(mode="json") for item in workspace_snapshot],
                    ensure_ascii=False,
                ),
                relevant_paths="\n".join(relevant_paths) or "Use the provided build output to infer the failing files.",
                attempt=repair_context.attempt,
                failed_command=repair_context.failed_command,
                build_error=repair_context.build_error,
            )
            response = model.invoke(messages)
            generation = parse_json_response(response.content, GeneratedCodeOutput)
            if relevant_paths and not any(item.path in set(relevant_paths) for item in generation.files):
                raise GenerationFailure(
                    "Qwen repair response did not update any file mentioned in the build failure context."
                )
            return generation
        except Exception as exc:
            if isinstance(exc, GenerationFailure):
                raise
            raise GenerationFailure(f"Qwen request failed while repairing generated code: {exc}") from exc

    @staticmethod
    def _derive_relevant_paths(workspace_snapshot: List[WorkspaceFile], build_error: str) -> List[str]:
        available_paths = {item.path for item in workspace_snapshot}
        relevant: List[str] = []

        for match in re.finditer(r"(?m)([A-Za-z0-9_./-]+\.(?:tsx?|jsx?|css|json|html))(?:\(|:)\d+", build_error):
            path = match.group(1)
            if path in available_paths and path not in relevant:
                relevant.append(path)

        if "Cannot find module" in build_error and "package.json" in available_paths and "package.json" not in relevant:
            relevant.append("package.json")

        for support_path in ("package.json", "tsconfig.json", "tsconfig.node.json", "vite.config.ts", "src/main.tsx"):
            if relevant and support_path in available_paths and support_path not in relevant:
                relevant.append(support_path)

        if relevant:
            return relevant

        fallback_paths = [
            path
            for path in ("package.json", "src/App.tsx", "src/main.tsx", "tsconfig.json", "vite.config.ts", "index.html")
            if path in available_paths
        ]
        return fallback_paths or [item.path for item in workspace_snapshot[:6]]

    @staticmethod
    def _select_repair_snapshot(workspace_snapshot: List[WorkspaceFile], relevant_paths: List[str]) -> List[WorkspaceFile]:
        if not relevant_paths:
            return workspace_snapshot

        selected = [item for item in workspace_snapshot if item.path in set(relevant_paths)]
        return selected or workspace_snapshot
